### PR TITLE
pgsql sanitation

### LINKED ISSUE #168: pgsql artisan migrate
error while trying to setup a new database with postgresql

```
Migrating: 2019_02_03_133007_change_id_type

In Connection.php line 664:
                                                                                                                                                              
  SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: ` bigint                                                                            
  LINE 1: update "photos" set "album_id_save" = `album_id`, "updated_a...                                                                                     
                                                ^                                                                                                             
  HINT:  No operator matches the given name and argument type. You might need to add an explicit type cast. (SQL: update "photos" set "album_id_save" = `alb  
  um_id`, "updated_at" = 2019-04-02 20:11:35 where "album_id_save" is null)                                                                                   
                                                                                                                                                              

In PDOStatement.php line 119:
                                                                                                             
  SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: ` bigint                           
  LINE 1: update "photos" set "album_id_save" = `album_id`, "updated_a...                                    
                                                ^                                                            
  HINT:  No operator matches the given name and argument type. You might need to add an explicit type cast.  
                                                                                                             

In PDOStatement.php line 117:
                                                                                                             
  SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: ` bigint                           
  LINE 1: update "photos" set "album_id_save" = `album_id`, "updated_a...                                    
                                                ^                                                            
  HINT:  No operator matches the given name and argument type. You might need to add an explicit type cast.
```

### PR DESCRIPTION
**Pull request by psjbeisler**
Fixes #168 

Confirmed working for me with a fresh Postgres database and fresh Lychee install
Thanks to @jprokop1 on #168

### CODE REVIEW

File: database/migrations/2019_02_03_133007_change_id_type.php [hunk 1]
```diff
@@ -30,31 +30,25 @@ public function up()
...
-				$table->dropForeign(['album_id']);
-			}
+		    $table->dropForeign(['album_id']);
 		    $table->dropColumn('album_id');
 	    });
 	    Schema::table('photos', function (Blueprint $table) {
-			if (DB::getDriverName() !== 'sqlite') {
-				$table->dropForeign(['album_id']);
-			}
+		    $table->dropForeign(['album_id']);
```
Comment (ildyria) [inline database/migrations/2019_02_03_133007_change_id_type.php]: Can you please add back the check for `sqlite` here ? :)

File: database/migrations/2019_02_03_133007_change_id_type.php [hunk 2]
```diff
@@ -30,31 +30,25 @@ public function up()
...
 		    $table->dropColumn('album_id');
 	    });
 	    Schema::table('albums', function (Blueprint $table) {
-			if (DB::getDriverName() !== 'sqlite') {
-				$table->dropForeign(['parent_id']);
-			}
+		    $table->dropForeign(['parent_id']);
```
Comment (ildyria) [inline database/migrations/2019_02_03_133007_change_id_type.php]: Can you please add back the check for `sqlite` here ? :)

File: database/migrations/2019_02_03_133007_change_id_type.php [hunk 3]
```diff
@@ -30,31 +30,25 @@ public function up()
...
 		DB::table('user_album')->where('album_id_save',null)->update([
-			"album_id_save" => DB::raw("`album_id`"),
+			'album_id_save' => DB::raw('album_id'),
 		]);
 
 	    Schema::table('user_album', function (Blueprint $table) {
-			if (DB::getDriverName() !== 'sqlite') {
-				$table->dropForeign(['album_id']);
-			}
+		    $table->dropForeign(['album_id']);
```
Comment (ildyria) [inline database/migrations/2019_02_03_133007_change_id_type.php]: Can you please add back the check for `sqlite` here ? :)

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 4]
```diff
@@ -17,55 +17,48 @@ class AddHidpi extends Migration
...
-
-				Schema::table('photos', function (Blueprint $table) {
-					$table->char('medium', 20)->default('');
-					$table->char('medium2x', 20)->default('');
-					$table->char('small', 20)->default('');
-					$table->char('small2x', 20)->default('');
-					$table->boolean('thumb2x')->default(true);
-				});
-			}
+		if (Schema::hasTable('configs')) {
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: Can you please add back the check for 
```php
if (!Schema::hasColumn('photos', 'thumb2x')) {
```
here ? :)
it is required so the migration can be rerun in case of that specific one fails.

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 5]
```diff
@@ -17,55 +17,48 @@ class AddHidpi extends Migration
...
+				],
+			]);
+		}
+		else {
+			echo "Table configs does not exists\n";
 		}
 
 		if (Schema::hasTable('photos')) {
+			Schema::table('photos', function (Blueprint $table) {
+				$table->renameColumn('medium', 'medium_old');
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: please split this into two query. cf previous version.

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 6]
```diff
@@ -80,26 +73,14 @@ public function up()
...
-					if (file_exists(Config::get('defines.dirs.LYCHEE_UPLOADS_MEDIUM').$photo->url)) {
-						list($width, $height) = getimagesize(Config::get('defines.dirs.LYCHEE_UPLOADS_MEDIUM').$photo->url);
-						$photo->medium = $width.'x'.$height;
-						$save = true;
-					}
-					else {
-						echo "Missing file ".Config::get('defines.dirs.LYCHEE_UPLOADS_MEDIUM').$photo->url."\n";
-						$this->failMessage();
-					}
+					list($width, $height) = getimagesize(Config::get('defines.dirs.LYCHEE_UPLOADS_MEDIUM').$photo->url);
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: the previous code is better here.

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 7]
```diff
@@ -80,26 +73,14 @@ public function up()
...
-					if (file_exists(Config::get('defines.dirs.LYCHEE_UPLOADS_SMALL').$photo->url)) {
-						list($width, $height) = getimagesize(Config::get('defines.dirs.LYCHEE_UPLOADS_SMALL').$photo->url);
-						$photo->small = $width.'x'.$height;
-						$save = true;
-					}
-					else {
-						echo "Missing file ".Config::get('defines.dirs.LYCHEE_UPLOADS_SMALL').$photo->url."\n";
-						$this->failMessage();
-					}
+					list($width, $height) = getimagesize(Config::get('defines.dirs.LYCHEE_UPLOADS_SMALL').$photo->url);
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: previous code is better here.

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 8]
```diff
@@ -108,7 +89,8 @@ public function up()
 			}
 
 			Schema::table('photos', function (Blueprint $table) {
-				$table->dropColumn('medium_old', 'small_old');
+				$table->dropColumn('medium_old');
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: previous code is better here.

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 9]
```diff
@@ -118,24 +100,6 @@ public function up()
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: We need the following function to allow the migration to crash (in case pictures where not found).

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 10]
```diff
@@ -150,12 +114,8 @@ public function down()
 
 			Schema::table('photos', function (Blueprint $table) {
 				$table->renameColumn('medium', 'medium_new');
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: Split this into two request.

File: database/migrations/2019_02_23_222617_add_hidpi.php [hunk 11]
```diff
@@ -180,7 +140,11 @@ public function down()
 			}
 
 			Schema::table('photos', function (Blueprint $table) {
-				$table->dropColumn('medium_new', 'medium2x', 'small_new', 'small2x', 'thumb2x');
+				$table->dropColumn('medium_new');
```
Comment (ildyria) [inline database/migrations/2019_02_23_222617_add_hidpi.php]: previous code was better here.

File: database/migrations/2019_02_03_133007_change_id_type.php [hunk 12]
```diff
@@ -40,16 +40,25 @@ public function up()
 		]);
 
 	    Schema::table('user_album', function (Blueprint $table) {
-		    $table->dropForeign(['album_id']);
-		    $table->dropColumn('album_id');
+        if (DB::getDriverName() !== 'sqlite') {
+          $table->dropForeign(['album_id']);
+        }
+        $table->dropForeign(['album_id']);
```
Comment (ildyria) [inline database/migrations/2019_02_03_133007_change_id_type.php]: you need to remove that line. You have a duplicate query here. It will try to drop twice which will break (most likely the reason why travis is complaining).

File: database/migrations/2019_02_03_133007_change_id_type.php [hunk 13]
```diff
@@ -40,16 +40,25 @@ public function up()
...
+        $table->dropColumn('album_id');
 	    });
 	    Schema::table('photos', function (Blueprint $table) {
-		    $table->dropForeign(['album_id']);
-		    $table->dropColumn('album_id');
+        if (DB::getDriverName() !== 'sqlite') {
+          $table->dropForeign(['album_id']);
+        }
+        $table->dropForeign(['album_id']);
```
Comment (ildyria) [inline database/migrations/2019_02_03_133007_change_id_type.php]: idem.

File: database/migrations/2019_02_03_133007_change_id_type.php [hunk 14]
```diff
@@ -40,16 +40,25 @@ public function up()
...
+        $table->dropColumn('album_id');
 	    });
 	    Schema::table('albums', function (Blueprint $table) {
-		    $table->dropForeign(['parent_id']);
-		    $table->dropColumn('parent_id');
+        if (DB::getDriverName() !== 'sqlite') {
+          $table->dropForeign(['parent_id']);
+        }
+        $table->dropForeign(['parent_id']);
```
Comment (ildyria) [inline database/migrations/2019_02_03_133007_change_id_type.php]: idem.

File: database/migrations/2019_02_03_133007_change_id_type.php (hunk 1 above)
Comment (psjbeisler) [reply database/migrations/2019_02_03_133007_change_id_type.php]: doesnt this become a duplicate entry then? for all 3 in this file

File: database/migrations/2019_02_03_133007_change_id_type.php (hunk 14 above)
Comment (psjbeisler) [reply database/migrations/2019_02_03_133007_change_id_type.php]: reverted

File: database/migrations/2019_02_03_133007_change_id_type.php (hunk 13 above)
Comment (psjbeisler) [reply database/migrations/2019_02_03_133007_change_id_type.php]: reverted

File: database/migrations/2019_02_03_133007_change_id_type.php (hunk 12 above)
Comment (psjbeisler) [reply database/migrations/2019_02_03_133007_change_id_type.php]: reverted

File: database/migrations/2019_02_03_133007_change_id_type.php (hunk 1 above)
Comment (ildyria) [reply database/migrations/2019_02_03_133007_change_id_type.php]: Fixed.

File: database/migrations/2019_02_03_133007_change_id_type.php (hunk 3 above)
Comment (ildyria) [reply database/migrations/2019_02_03_133007_change_id_type.php]: Fixed

File: database/migrations/2019_02_23_222617_add_hidpi.php (hunk 4 above)
Comment (ildyria) [reply database/migrations/2019_02_23_222617_add_hidpi.php]: Fixed

File: database/migrations/2019_02_23_222617_add_hidpi.php (hunk 7 above)
Comment (ildyria) [reply database/migrations/2019_02_23_222617_add_hidpi.php]: fixed.

File: database/migrations/2019_02_23_222617_add_hidpi.php (hunk 5 above)
Comment (ildyria) [reply database/migrations/2019_02_23_222617_add_hidpi.php]: fixed.

File: database/migrations/2019_02_23_222617_add_hidpi.php (hunk 6 above)
Comment (ildyria) [reply database/migrations/2019_02_23_222617_add_hidpi.php]: fixed

File: database/migrations/2019_02_23_222617_add_hidpi.php (hunk 9 above)
Comment (ildyria) [reply database/migrations/2019_02_23_222617_add_hidpi.php]: fixed

File: database/migrations/2019_02_23_222617_add_hidpi.php (hunk 10 above)
Comment (ildyria) [reply database/migrations/2019_02_23_222617_add_hidpi.php]: fixed

File: database/migrations/2019_02_03_133007_change_id_type.php (hunk 2 above)
Comment (ildyria) [reply database/migrations/2019_02_03_133007_change_id_type.php]: fixed

**Comment by psjbeisler** [comment]
Thanks, i was too tired to finish this
